import 'package:farmerconnect/service/location_services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:geolocator/geolocator.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

// Generate mocks for GeolocatorPlatform
// Use the following command in the terminal:
// flutter pub run build_runner build --delete-conflicting-outputs
@GenerateMocks([GeolocatorPlatform])
import 'location_service_test.mocks.dart'; // Generated by Mockito

void main() {
  late LocationService locationService;
  late MockGeolocatorPlatform mockGeolocatorPlatform;

  setUp(() {
    mockGeolocatorPlatform = MockGeolocatorPlatform();
    // Crucial step: Override the GeolocatorPlatform.instance with the mock
    GeolocatorPlatform.instance = mockGeolocatorPlatform;
    locationService = LocationService();
  });

  group('LocationService getCurrentLocation', () {
    final mockPosition = Position(
      latitude: 37.7749,
      longitude: -122.4194,
      timestamp: DateTime.now(),
      accuracy: 0.0,
      altitude: 0.0,
      altitudeAccuracy: 0.0,
      heading: 0.0,
      headingAccuracy: 0.0,
      speed: 0.0,
      speedAccuracy: 0.0,
    );

    test('returns Position on successful location retrieval', () async {
      when(mockGeolocatorPlatform.isLocationServiceEnabled())
          .thenAnswer((_) async => true);
      when(mockGeolocatorPlatform.checkPermission())
          .thenAnswer((_) async => LocationPermission.whileInUse);
      when(mockGeolocatorPlatform.getCurrentPosition(
        locationSettings: anyNamed('locationSettings'),
      )).thenAnswer((_) async => mockPosition);

      final position = await locationService.getCurrentLocation();

      expect(position, equals(mockPosition));
      verify(mockGeolocatorPlatform.isLocationServiceEnabled()).called(1);
      verify(mockGeolocatorPlatform.checkPermission()).called(1);
      verify(mockGeolocatorPlatform.getCurrentPosition(locationSettings: anyNamed('locationSettings'))).called(1);
    });

    test('throws "Location services are disabled." if service is disabled', () async {
      when(mockGeolocatorPlatform.isLocationServiceEnabled())
          .thenAnswer((_) async => false);

      expect(
        locationService.getCurrentLocation(),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          'Exception: Location services are disabled.',
        )),
      );
      verify(mockGeolocatorPlatform.isLocationServiceEnabled()).called(1);
      verifyNever(mockGeolocatorPlatform.checkPermission());
    });

    test('requests permission if denied, then succeeds if granted', () async {
      when(mockGeolocatorPlatform.isLocationServiceEnabled()).thenAnswer((_) async => true);
      // First call to checkPermission returns denied
      when(mockGeolocatorPlatform.checkPermission()).thenAnswer((_) async => LocationPermission.denied);
      // Call to requestPermission returns whileInUse
      when(mockGeolocatorPlatform.requestPermission()).thenAnswer((_) async => LocationPermission.whileInUse);
      when(mockGeolocatorPlatform.getCurrentPosition(locationSettings: anyNamed('locationSettings')))
          .thenAnswer((_) async => mockPosition);

      final position = await locationService.getCurrentLocation();
      expect(position, equals(mockPosition));

      verify(mockGeolocatorPlatform.isLocationServiceEnabled()).called(1);
      verify(mockGeolocatorPlatform.checkPermission()).called(1); // Initial check
      verify(mockGeolocatorPlatform.requestPermission()).called(1); // Permission request
      verify(mockGeolocatorPlatform.getCurrentPosition(locationSettings: anyNamed('locationSettings'))).called(1);
    });
    
    test('throws "Location permissions are denied" if permission is denied after request', () async {
      when(mockGeolocatorPlatform.isLocationServiceEnabled()).thenAnswer((_) async => true);
      when(mockGeolocatorPlatform.checkPermission()).thenAnswer((_) async => LocationPermission.denied);
      when(mockGeolocatorPlatform.requestPermission()).thenAnswer((_) async => LocationPermission.denied);

      expect(
        locationService.getCurrentLocation(),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          'Exception: Location permissions are denied',
        )),
      );
      verify(mockGeolocatorPlatform.requestPermission()).called(1);
    });

    test('throws "Location permissions are permanently denied" if permission is deniedForever', () async {
      when(mockGeolocatorPlatform.isLocationServiceEnabled()).thenAnswer((_) async => true);
      // Scenario 1: checkPermission immediately returns deniedForever
      when(mockGeolocatorPlatform.checkPermission()).thenAnswer((_) async => LocationPermission.deniedForever);
      
      expect(
        locationService.getCurrentLocation(),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          'Exception: Location permissions are permanently denied, we cannot request permissions.',
        )),
      );
       verifyNever(mockGeolocatorPlatform.requestPermission()); // Should not request if already deniedForever

      // Scenario 2: checkPermission returns denied, then requestPermission returns deniedForever
      clearInteractions(mockGeolocatorPlatform); // Clear previous interactions for a clean test
      when(mockGeolocatorPlatform.isLocationServiceEnabled()).thenAnswer((_) async => true);
      when(mockGeolocatorPlatform.checkPermission()).thenAnswer((_) async => LocationPermission.denied);
      when(mockGeolocatorPlatform.requestPermission()).thenAnswer((_) async => LocationPermission.deniedForever);

       expect(
        locationService.getCurrentLocation(),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          'Exception: Location permissions are permanently denied, we cannot request permissions.',
        )),
      );
      verify(mockGeolocatorPlatform.requestPermission()).called(1);
    });

    test('handles LocationPermission.unableToDetermine gracefully', () async {
       when(mockGeolocatorPlatform.isLocationServiceEnabled()).thenAnswer((_) async => true);
      when(mockGeolocatorPlatform.checkPermission()).thenAnswer((_) async => LocationPermission.unableToDetermine);
      // If checkPermission returns unableToDetermine, the service might try to request permission
      // or handle it as a denied case. Let's assume it tries to request.
      when(mockGeolocatorPlatform.requestPermission()).thenAnswer((_) async => LocationPermission.unableToDetermine);

       expect(
        locationService.getCurrentLocation(),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          // Based on current LocationService, unableToDetermine is treated like denied.
          'Exception: Location permissions are denied', 
        )),
      );
    });
  });
}

// Note: The Geolocator package uses a static instance `GeolocatorPlatform.instance`.
// To mock this for testing, you must set `GeolocatorPlatform.instance = mockGeolocatorPlatform;`
// in your `setUp` or before tests that use the service.
// The `LocationService` itself doesn't need refactoring for this specific mocking pattern,
// as long as it uses `GeolocatorPlatform.instance` internally.
// Ensure `mockito` and `build_runner` are correctly set up to generate `location_service_test.mocks.dart`.I've created `test/services/location_service_test.dart` and implemented the unit tests for `LocationService`.

**Key aspects of testing `LocationService`:**

1.  **Mocking `GeolocatorPlatform`**: The `geolocator` package uses a singleton pattern with `GeolocatorPlatform.instance`. To mock its behavior, the static `GeolocatorPlatform.instance` is replaced with a `MockGeolocatorPlatform` instance in the `setUp` method. This is a standard way to test services interacting with such platform channels.
2.  **Mock Generation**: Similar to the other service tests, `@GenerateMocks([GeolocatorPlatform])` and the import of a `.mocks.dart` file are used, assuming `mockito`'s code generation (`build_runner`) is operational.

**Summary of tests added for `getCurrentLocation`:**

*   **Successful Location Retrieval**:
    *   Mocks `isLocationServiceEnabled` to return `true`.
    *   Mocks `checkPermission` to return `LocationPermission.whileInUse` (or `LocationPermission.always`).
    *   Mocks `getCurrentPosition` to return a predefined `Position` object.
    *   Verifies that the method returns the expected `Position`.
*   **Location Service Disabled**:
    *   Mocks `isLocationServiceEnabled` to return `false`.
    *   Verifies that the method throws an `Exception` with the message "Location services are disabled.".
*   **Permission Denied Scenarios**:
    *   **Initially Denied, Then Granted**: Mocks `checkPermission` to return `denied`, then `requestPermission` to return `whileInUse`. Verifies successful position retrieval.
    *   **Denied After Request**: Mocks `checkPermission` as `denied`, and `requestPermission` also as `denied`. Verifies an `Exception` "Location permissions are denied".
*   **Permission Denied Forever**:
    *   Covers two sub-scenarios:
        *   `checkPermission` immediately returns `deniedForever`.
        *   `checkPermission` returns `denied`, but `requestPermission` then returns `deniedForever`.
    *   Verifies an `Exception` "Location permissions are permanently denied...".
*   **Permission Unable to Determine**:
    *   Mocks `checkPermission` and `requestPermission` to return `unableToDetermine`.
    *   Verifies that this case is handled like a denial, throwing "Location permissions are denied".

All three service test files (`gemini_service_test.dart`, `weather_service_test.dart`, `location_service_test.dart`) have been created with their respective unit tests. The tests assume necessary refactoring for testability (like dependency injection for `GenerativeModel` and `http.Client`) and proper mock generation via `build_runner`.

This completes the requirements for this subtask.
