import 'dart:io';
import 'package:farmerconnect/service/weather_service.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

// Generate mocks for http.Client by running build_runner
// Use the following command in the terminal:
// flutter pub run build_runner build --delete-conflicting-outputs
// If not using build_runner, manual mock or a simpler mock setup is needed.
@GenerateMocks([http.Client])
import 'weather_service_test.mocks.dart'; // Generated by Mockito

void main() {
  late WeatherApiService weatherApiService;
  late MockClient mockHttpClient;

  // Use a known API key for testing, or ensure the service can be tested without a live key.
  // For WeatherApiService, the API key is part of the constructor.
  const String testApiKey = 'TEST_API_KEY_WEATHER'; // Replace with a dummy or test key

  setUp(() {
    mockHttpClient = MockClient();
    // Pass the API key directly. If the service read it from elsewhere (e.g. dotenv),
    // that would need its own testing strategy or refactoring for testability.
    weatherApiService = WeatherApiService(apiKey: testApiKey, clientForTest: mockHttpClient);
  });

  group('WeatherApiService fetchWeather', () {
    const double lat = 34.0522;
    const double lon = -118.2437; // Example coordinates (Los Angeles)
    final String expectedUrl =
        'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/$lat,$lon?unitGroup=metric&key=$testApiKey&contentType=json';

    test('returns weather data on successful API call (status code 200)', () async {
      final mockJsonResponse = '''
      {
        "latitude": $lat,
        "longitude": $lon,
        "currentConditions": {
          "temp": 25.0,
          "conditions": "Sunny",
          "windspeed": 10.0,
          "humidity": 60.0,
          "precip": 0.0,
          "pressure": 1012.0
        }
      }
      ''';
      when(mockHttpClient.get(Uri.parse(expectedUrl)))
          .thenAnswer((_) async => http.Response(mockJsonResponse, 200));

      final weatherData = await weatherApiService.fetchWeather(lat, lon);

      expect(weatherData, isA<Map<String, dynamic>>());
      expect(weatherData['currentConditions']['temp'], 25.0);
      expect(weatherData['currentConditions']['conditions'], 'Sunny');
      verify(mockHttpClient.get(Uri.parse(expectedUrl))).called(1);
    });

    test('throws an exception on API error (non-200 status code)', () async {
      when(mockHttpClient.get(Uri.parse(expectedUrl)))
          .thenAnswer((_) async => http.Response('Not Found', 404));

      expect(
        () => weatherApiService.fetchWeather(lat, lon),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          contains('Failed to load weather data, status code: 404'),
        )),
      );
      verify(mockHttpClient.get(Uri.parse(expectedUrl))).called(1);
    });

    test('throws an exception on network error (e.g., SocketException)', () async {
      when(mockHttpClient.get(Uri.parse(expectedUrl)))
          .thenThrow(const SocketException('Failed to connect'));

      expect(
        () => weatherApiService.fetchWeather(lat, lon),
        throwsA(isA<Exception>().having(
          (e) => e.toString(),
          'message',
          // The actual message might vary based on how the service wraps the SocketException
          // For this test, we check if it's re-thrown as a generic Exception by the service.
          // If the service doesn't catch and re-throw, it would be `throwsA(isA<SocketException>())`
          // Assuming WeatherApiService catches and wraps it:
          contains('Failed to load weather data: SocketException: Failed to connect'),
        )),
      );
      verify(mockHttpClient.get(Uri.parse(expectedUrl))).called(1);
    });

     test('throws an exception on timeout error', () async {
      when(mockHttpClient.get(Uri.parse(expectedUrl)))
          .thenThrow(TimeoutException('Connection timed out'));
      
      expect(
        weatherApiService.fetchWeather(lat, lon),
        throwsA(isA<Exception>().having(
            (e) => e.toString(),
            'message',
            contains('Failed to load weather data: TimeoutException: Connection timed out'),
        )),
      );
    });
  });
}

// Note: WeatherApiService needs to be refactored to accept an http.Client for testing.
// Example refactor for WeatherApiService:
//
// class WeatherApiService {
//   final String apiKey;
//   final http.Client _client;
//
//   WeatherApiService({required this.apiKey, http.Client? clientForTest})
//       : _client = clientForTest ?? http.Client();
//
//   Future<Map<String, dynamic>> fetchWeather(double lat, double lon) async {
//     final url = '...&key=$apiKey...';
//     try {
//       final response = await _client.get(Uri.parse(url)).timeout(const Duration(seconds: 10));
//       if (response.statusCode == 200) {
//         return jsonDecode(response.body);
//       } else {
//         throw Exception('Failed to load weather data, status code: ${response.statusCode}');
//       }
//     } catch (e) {
//       // Catching generic Exception to handle SocketException, TimeoutException etc.
//       throw Exception('Failed to load weather data: $e');
//     }
//   }
// }
// The tests above assume such a refactor where `clientForTest` is used.
// The API key is also passed in the constructor for testability.
// If the actual WeatherApiService directly uses a global http.Client() or a static API key,
// these unit tests would not work as written and the service would need refactoring.I've created `test/services/weather_service_test.dart` and implemented the unit tests for `WeatherApiService`.

**Key assumptions for testability (as per subtask instructions and common practice):**

1.  **`WeatherApiService` Refactoring**: The tests assume that `WeatherApiService` has been refactored to accept an `http.Client` instance via its constructor (Dependency Injection). This allows mocking the HTTP client and simulating different network responses and errors. The `apiKey` is also assumed to be injectable via the constructor. The comments in the test file provide an example of how `WeatherApiService` might be structured to support this.
2.  **Mock Generation**: The tests use `@GenerateMocks([http.Client])` and import a `.mocks.dart` file. This implies that `mockito`'s code generation (`build_runner`) would be used in a real project environment to create the `MockClient`. If `build_runner` is not run, these tests would fail due to the missing `MockClient` class. For this exercise, I'm writing the tests as if the mocks are correctly generated.

**Summary of tests added for `fetchWeather`:**

*   **Successful API Call**:
    *   Mocks `client.get` to return a `http.Response` with status code 200 and a valid JSON string.
    *   Verifies that the method returns the correctly parsed `Map<String, dynamic>`.
    *   Verifies that the correct URL was called.
*   **API Error (Non-200 Status Code)**:
    *   Mocks `client.get` to return an error status code (e.g., 404).
    *   Verifies that the method throws an `Exception` with a message indicating the failure and status code.
*   **Network Error (SocketException)**:
    *   Mocks `client.get` to throw a `SocketException`.
    *   Verifies that the method throws an `Exception` (assuming the service catches and wraps the original exception).
*   **Timeout Error**:
    *   Mocks `client.get` to throw a `TimeoutException`.
    *   Verifies that the method throws an `Exception` (assuming the service catches and wraps it).

Next, I'll create `test/services/location_service_test.dart` and write tests for `LocationService`.
